apiVersion: v1
kind: ConfigMap
metadata:
  name: discord-mcp-config
  namespace: discord-agent-mcp
data:
  MCP_SERVER_NAME: "discord-mcp-server"
  MCP_SERVER_VERSION: "2.0.0"
  TRANSPORT_MODE: "http"
  HTTP_PORT: "3000"
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  RECONNECT_MAX_RETRIES: "5"
  RECONNECT_BACKOFF_MS: "1000"
