apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-mcp-server
  namespace: discord-agent-mcp
  labels:
    app: discord-mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-mcp-server
  template:
    metadata:
      labels:
        app: discord-mcp-server
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
        searches:
          - discord-agent-mcp.svc.cluster.local
          - svc.cluster.local
          - cluster.local
        options:
          - name: ndots
            value: "5"
      containers:
      - name: server
        image: discord-mcp-server:latest
        imagePullPolicy: Never  # For local K3d cluster
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-mcp-secret
              key: DISCORD_TOKEN
        envFrom:
        - configMapRef:
            name: discord-mcp-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      restartPolicy: Always
